# Generated by Django 3.1 on 2020-09-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20200908_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area_hectares',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
